In [44]:
import torch
import matplotlib.pyplot as plt
%matplotlib inline

In [45]:
with open('data.txt', 'r') as f:
    data = f.readlines()

In [53]:
# inputs
xs = torch.Tensor([float(i) for i in data[0].split(',')])   ; requires_grad=True 

# weights
w = torch.randn(len(data[0]))   ; requires_grad=True  

# targets
ys = torch.Tensor([float(i) for i in data[1].split(',')])

print(xs)
print(w)
print(ys)

tensor([12.,  5., 29., 16., 32., 20., 27., 11.,  4.,  2.,  1., 10., 29., 15.,
        18.])
tensor([ 0.3857,  0.8166,  0.6947,  0.5852,  1.8635, -1.6936,  1.5856, -0.7252,
        -1.1014, -0.2945, -0.6604,  1.2609,  2.2745, -0.6434, -0.2602, -0.8861,
         0.6536,  1.0470, -0.5381, -1.2227, -0.7206,  0.0630,  0.5453, -1.1172,
        -0.2063,  0.1457, -0.4586,  0.1039,  1.3490, -0.1702,  1.2319,  0.5207,
        -0.3168,  2.1176, -0.1136, -0.6676, -0.5259,  0.4173, -0.0478, -1.6269,
        -0.1849,  0.9662, -0.0656, -2.1536, -0.8617,  1.0219, -0.0502,  0.5226,
        -0.3392,  1.1991,  0.6344, -0.6681,  0.4903,  1.4146,  0.3450, -0.4018])
tensor([10.8000,  3.6000, 13.6000,  8.6000, 24.1000, 14.3000, 20.1000, 11.6000,
        20.6000,  7.2000,  5.6000, 14.3000,  7.6000, 23.0000,  7.7000])
